from os import PathLike
from typing import Any, AnyStr, Optional
from .timelib import Timescale

class Loader:
    def __init__(self, directory: PathLike[AnyStr], verbose: bool = ..., expire: bool = ...): ...
    def __call__(self, filename: str, reload: bool = ..., backup: bool = ..., builtin: bool = ...) -> Any: ...
    def timescale(self, delta_t: Optional[int | float] = ..., builtin: bool = ...) -> Timescale: ...