from typing import Optional
from .framelib import EclipticFrame
from .units import Angle, Distance
from .vectorlib import VectorFunction

class ICRF:
    def altaz(self, temperature_C: Optional[float | str] = ..., pressure_mbar: float | str = ...) -> tuple[Angle, Angle, Distance]: ...
    def frame_latlon(self, frame: EclipticFrame) -> tuple[Angle, Angle, Distance]: ...

class Apparent(ICRF): ...

class Astrometric(ICRF):
    def apparent(self) -> Apparent: ...

class Barycentric(ICRF):
    def observe(self, body: VectorFunction) -> Astrometric: ...

class Geocentric(ICRF): ...
