from collections.abc import Iterable
from datetime import date, datetime, timedelta
from numpy import float64, ndarray

class Timescale:
    def now(self) -> Time: ...
    def utc(self, year: datetime | date | Iterable[datetime] | int, month: int = ..., day: int = ..., hour: int = ..., minute: int = ..., second: float = ...) -> Time: ...

class Time:
    def __sub__(self, other: Time | timedelta | int | float) -> float64: ...
    def utc_datetime(self) -> ndarray | datetime: ...
    _nutation_angles_radians: tuple[float, float]